# = display constants
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
GAME_WIDTH = 640
GAME_HEIGHT = 360
LINE_WIDTH = 2


# = player constants
PLAYER_RADIUS = 15
PLAYER_SPEED = 100
PLAYER_TURN_SPEED = 300
PLAYER_SHOOT_SPEED = 300
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# = asteroid constants
ASTEROID_MIN_RADIUS = 15
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# = bullet constants
SHOT_RADIUS = 5
